#packmode expert
mods.extendedcrafting.TableCrafting.addShaped("infinity_helmet", 0, <item:avaritia:infinity_helmet>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:draconicevolution:chaotic_core>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:projecte:gem_helmet> | <item:projecte:gem_helmet>.withTag({}), <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_chestplate", 0, <item:avaritia:infinity_chestplate>, [
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:projecte:gem_chestplate> | <item:projecte:gem_chestplate>.withTag({}), <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:draconicevolution:chaotic_core>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_pants", 0, <item:avaritia:infinity_pants>, [
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:draconicevolution:chaotic_core>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:projecte:gem_leggings> | <item:projecte:gem_leggings>.withTag({}), <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_boots", 0, <item:avaritia:infinity_boots>, [
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:projecte:gem_boots> | <item:projecte:gem_boots>.withTag({}), <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:draconicevolution:chaotic_core>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);