#packmode expert
craftingTable.removeByName("mysticalagriculture:soul_extractor");
craftingTable.removeByName("mysticalagriculture:tinkering_table");
craftingTable.removeByName("mysticalagriculture:upgrade_base");
craftingTable.removeByName("mysticalagriculture:inferium_furnace");
craftingTable.addShaped("soul_extractor", <item:mysticalagriculture:soul_extractor>, [[<tag:items:forge:ingots/invar>, <item:mysticalagriculture:soulium_ingot>, <tag:items:forge:ingots/invar>], [<item:mysticalagriculture:soulium_dagger>, <item:mysticalagriculture:machine_frame>, <item:mysticalagriculture:soulium_dagger>], [<tag:items:forge:gears/enderium>, <item:mysticalagriculture:soulium_ingot>, <tag:items:forge:gears/enderium>]]);
craftingTable.addShaped("tinkering_table", <item:mysticalagriculture:tinkering_table>, [[<item:ad_astra:moon_stone>, <item:ad_astra:moon_stone>, <item:ad_astra:moon_stone>], [<item:mysticalagriculture:soulium_dust>, <item:ad_astra:moon_stone>, <item:mysticalagriculture:soulium_dust>], [<item:ad_astra:moon_stone>, <item:ad_astra:moon_stone>, <item:ad_astra:moon_stone>]]);
craftingTable.addShaped("upgrade_base", <item:mysticalagriculture:upgrade_base>, [[<item:mysticalagriculture:prosperity_shard>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:prosperity_shard>], [<item:mysticalagriculture:prosperity_ingot>, <item:pneumaticcraft:upgrade_matrix>, <item:mysticalagriculture:prosperity_ingot>], [<item:mysticalagriculture:prosperity_shard>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:prosperity_shard>]]);
craftingTable.addShaped("inferium_furnace", <item:mysticalagriculture:inferium_furnace>, [[<item:minecraft:air>, <item:mysticalagriculture:inferium_essence>, <item:minecraft:air>], [<item:mysticalagriculture:inferium_ingot>, <item:ironfurnaces:diamond_furnace>, <item:mysticalagriculture:inferium_ingot>], [<item:minecraft:air>, <item:mysticalagriculture:inferium_block>, <item:minecraft:air>]]);
