<recipetype:immersiveengineering:metal_press>.addJsonRecipe("netherite_plate",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"tag":"forge:ingots/netherite"},"mold":"immersiveengineering:mold_plate","result":{"tag":"forge:plates/netherite"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("signalum_plate",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"tag":"forge:ingots/signalum"},"mold":"immersiveengineering:mold_plate","result":{"tag":"forge:plates/signalum"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("lumium_plate",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"tag":"forge:ingots/lumium"},"mold":"immersiveengineering:mold_plate","result":{"tag":"forge:plates/lumium"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("enderium_plate",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"tag":"forge:ingots/enderium"},"mold":"immersiveengineering:mold_plate","result":{"tag":"forge:plates/enderium"}});
craftingTable.removeByName("industrialforegoing:diamond_gear");
craftingTable.removeByName("industrialforegoing:iron_gear");
craftingTable.removeByName("industrialforegoing:gold_gear");
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("compressed_iron_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:ingots/compressed_iron"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/compressed_iron"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("netherite_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:ingots/netherite"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"item":"thermal:netherite_gear"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("signalum_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:ingots/signalum"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/signalum"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("lumium_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:ingots/lumium"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/lumium"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("enderium_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:ingots/enderium"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/enderium"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("lapis_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/lapis"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/lapis"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("diamond_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/diamond"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"item":"thermal:diamond_gear"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("emerald_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/emerald"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/emerald"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("quartz_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/quartz"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/quartz"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("ruby_gear_press",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/ruby"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/ruby"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("sapphire_gear_press",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"tag":"forge:gems/sapphire"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"tag":"forge:gears/sapphire"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("flux-infused_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"item":"redstone_arsenal:flux_ingot"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"item":"redstone_arsenal:flux_gear"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("neutronium_gear",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"base_ingredient":{"item":"avaritia:neutron_ingot"},"count":4},"mold":"immersiveengineering:mold_gear","result":{"item":"avaritia:neutron_gear"}});
<recipetype:immersiveengineering:metal_press>.addJsonRecipe("black_iron_slate",
{"type":"immersiveengineering:metal_press","energy":2400,"input":{"item":"extendedcrafting:black_iron_ingot"},"mold":"immersiveengineering:mold_plate","result":{"item":"extendedcrafting:black_iron_slate"}});
