mods.mysticalagriculture.InfusionCrafting.remove(<item:mysticalagriculture:infinity_catalyst_seeds>);
mods.mysticalagriculture.InfusionCrafting.addRecipe("infinityseeds", <item:mysticalagriculture:infinity_catalyst_seeds>, [<item:kubejs:demon_steel_tier_4>, <item:avaritia:infinity_catalyst>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity_catalyst>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity_catalyst>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity_catalyst>, <item:mysticalagradditions:insanium_essence>]);
mods.mysticalagriculture.InfusionCrafting.remove(<item:mysticalagriculture:infinity_nugget_seeds>);
mods.mysticalagriculture.InfusionCrafting.addRecipe("infinitynuggetseeds", <item:mysticalagriculture:infinity_nugget_seeds>, [<item:kubejs:chaos_ingot>, <item:avaritia:infinity>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity>, <item:mysticalagradditions:insanium_essence>, <item:avaritia:infinity>, <item:mysticalagradditions:insanium_essence>]);

mods.mysticalagriculture.InfusionCrafting.remove(<item:mysticalagriculture:nether_star_block_seeds>);
mods.mysticalagriculture.InfusionCrafting.addRecipe("netherstarblockseeds", <item:mysticalagriculture:nether_star_block_seeds>, [<item:kubejs:demon_steel_tier_4>, <item:extendedcrafting:nether_star_block>, <item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:nether_star_block>, <item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:nether_star_block>, <item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:nether_star_block>, <item:mysticalagradditions:insanium_essence>]);
mods.mysticalagriculture.InfusionCrafting.remove(<item:mysticalagriculture:klein_star_block_seeds>);
mods.mysticalagriculture.InfusionCrafting.addRecipe("kleinstarblockseeds", <item:mysticalagriculture:klein_star_block_seeds>, [<item:kubejs:chaos_ingot>, <item:kubejs:klein_star_block>, <item:mysticalagradditions:insanium_essence>, <item:kubejs:klein_star_block>, <item:mysticalagradditions:insanium_essence>, <item:kubejs:klein_star_block>, <item:mysticalagradditions:insanium_essence>, <item:kubejs:klein_star_block>, <item:mysticalagradditions:insanium_essence>]);
