ItemEvents.tooltip(event => {
  event.add(['javd:portal_block'], '§cMay cause lag and tps issues!')
  event.add(['framedcompactdrawers:framed_compact_drawer'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_drawer_controller'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_slave'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_trim'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_full_one'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_full_two'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_full_four'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_half_one'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_half_two'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(['framedcompactdrawers:framed_half_four'], '§cDeprecated - if your drawers are gone, downgrade and load a backup, then recover items and update!')
  event.add(/betterfurnacesreforged:/, '§cDeprecated - use Iron Furnaces mod instead!')
})