<recipetype:mekanism:crushing>.addRecipe("dust", <item:minecraft:sand>, <item:exdeorum:dust>);
<recipetype:mekanism:crushing>.addRecipe("crushed_netherrack", <item:minecraft:netherrack>, <item:exdeorum:crushed_netherrack>);
<recipetype:mekanism:crushing>.addRecipe("crushed_endstone", <item:minecraft:end_stone>, <item:exdeorum:crushed_end_stone>);
<recipetype:mekanism:crushing>.addRecipe("crushed_deepslate", <item:minecraft:cobbled_deepslate>, <item:exdeorum:crushed_deepslate>);
<recipetype:mekanism:crushing>.addRecipe("crushed_blackstone", <item:minecraft:blackstone>, <item:exdeorum:crushed_blackstone>);
<recipetype:mekanism:crushing>.addRecipe("hop_dust", <item:immersiveengineering:ingot_hop_graphite>, <item:immersiveengineering:dust_hop_graphite>);
<recipetype:mekanism:crushing>.addRecipe("crush_nickel", <tag:items:forge:ingots/nickel>, <item:immersiveengineering:dust_nickel>);
<recipetype:mekanism:crushing>.addRecipe("crush_silver", <tag:items:forge:ingots/silver>, <item:immersiveengineering:dust_silver>);
<recipetype:mekanism:crushing>.addRecipe("crush_aluminum", <tag:items:forge:ingots/aluminum>, <item:immersiveengineering:dust_aluminum>);